# Generated by Django 3.2.7 on 2021-09-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210928_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='notebook',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='category',
            new_name='categories',
        ),
    ]
